steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [config, get-value, account]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: git
  args: [fetch, --unshallow, --tags]
- name: node:14
  entrypoint: yarn
  env:
  - NODE_ENV=production
  args: [--frozen-lockfile]
- name: node:14
  entrypoint: yarn
  args: [deploy]
  env:
  - ENVIRONMENT=${_ENVIRONMENT}
- name: node:14
  entrypoint: yarn
  args: [update-dev-database]

substitutions:
    _ENVIRONMENT: dev

artifacts:
  objects:
    location: gs://chromebooks-in-deutschland-logs/$BUILD_ID
    paths: [backup.json]
