steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [config, get-value, account]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: git
  args: [fetch, --unshallow, --tags]
- name: node
  entrypoint: yarn
  args: [install]
- name: node
  entrypoint: yarn
  args: [run, deploy]
  env:
  - ENVIRONMENT=${_ENVIRONMENT}
- name: node
  entrypoint: yarn
  args: [run, update-dev-database]

substitutions:
    _ENVIRONMENT: dev

artifacts:
  objects:
    location: gs://chromebooks-in-deutschland-logs/$BUILD_ID
    paths: [backup.json]
