version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # workaround for expired yarn apt repo key
      # https://github.com/yarnpkg/yarn/issues/7866
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update
      - apt-get -y install build-essential curl file git
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - source ~/.profile
      - brew install terraform terragrunt awscli
  build:
    commands:
      - ls -lR
      - git status --verbose
      - yarn --prod --frozen-lockfile
      - yarn prep
      - cd aws
      - terragrunt plan tf.plan
      - terragrunt apply -auto-approve tf.plan


