version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - docker info
  build:
    commands:
      - ls -lR
      - git status --verbose
      - yarn --prod --frozen-lockfile
      - yarn prep
      - docker run --rm
        -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        amazon/aws-cli sts get-caller-identity
      - docker run --rm 
        -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        -v $(pwd):$(pwd) -u $(id -u):$(id -g)
        -w $(pwd)/aws 
        alpine/terragrunt
        ./plan.sh
      - export $(
          docker run --rm 
          -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
          -v $(pwd):$(pwd) -u $(id -u):$(id -g)
          -w $(pwd)/aws
          mozilla/sops:alpine --verbose -d build_secrets.env
        )
      - aws/cloudrail.sh
      - docker run --rm 
        -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        -v $(pwd):$(pwd) -u $(id -u):$(id -g)
        -w $(pwd)/aws
        alpine/terragrunt
        ./apply.sh

# Notes:
# Docker requires the privileged flag in the CodeBuild configuration
# AWS credential passing https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-versions
