#!/bin/bash
# https://docs.docker.com/docker-hub/builds/advanced/

if [[ "DOCKER_TAG" == v* ]] ; then
    echo "=> Setting release tag"
    tag="$DOCKER_REPO:release"
    docker tag $IMAGE_NAME "$tag"
    docker push "$tag"
fi

if test -r VERSION ; then
    read -r VERSION <VERSION
    echo "=> Setting $VERSION tag"
    tag="$DOCKER_REPO:$VERSION"
    docker push "$tag"
fi