# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Release Agent

on:
  push:
    branches: [ master ]
    tags: ["v*"]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Setup package build
      run: sudo apt install -yV --no-install-recommends build-essential devscripts lintian
    - run: yarn --frozen-lockfile
    - run: yarn prep
    - id: version
      name: Check & Set VERSION
      run: |
        echo "::set-output name=VERSION::$(<VERSION)"
        echo "::set-output name=container_tag::$IMAGE_NAME:$(<VERSION)"

        grep -v dirty VERSION || { git status ; exit 1 ; }

    - run: yarn binary-build
    - run: yarn deb-build


    - name: GitHub & Container Release
      id: release
      if: github.event_name == 'push' && contains(github.ref, '/tags/v')
      env:
        TAG: ${{ github.ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "$TAG" dist/*
        echo "::set-output name=container_tag::$IMAGE_NAME:prod"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set dev Container tag
      run: |
        echo "::set-output name=container_tag::$IMAGE_NAME:dev"

    - run: |
        echo "ARRAY: --->${{ steps.*.outputs.container_tag }}<---"
        echo "JOIN: --->${{ join(steps.*.outputs.container_tag, ',') }}<---"

    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        # Container push only for push, not on PR
        push: ${{ github.event_name == 'push' }} 
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7
        tags: ${{ join(steps.*.outputs.container_tag, ',') }}
  
    - name: Upload build artifacts
      uses: 'actions/upload-artifact@v2'
      with:
          path: dist/*
          name: chromebooks-in-deutschland-${{ steps.version.outputs.VERSION }}
