# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    tags: ["v*"]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn binary
    - id: version
      name: Set VERSION
      run: echo "::set-output name=VERSION::$(<VERSION)"
    - name: Upload
      uses: 'actions/upload-artifact@v2'
      with:
          path: dist/*
          name: cid-${{ steps.version.outputs.VERSION }}
    - name: Upload
      uses: 'actions/upload-artifact@v2'
      with:
          path: dist/*macos*
